export const PHOTOS = [
  {
    url: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAIA3qGHyYKUZMU0jD-kJ_7t8NVwwKOLeXUFlZQ0NLdiIhWsxQGOlZ8lYgAcLs-zTZp0lHHze33oIX9xKCLjkgYvgidlbjcTUW6xB--qw5T_Nh-vhWOvRKdxSoMwHxhkOgVy2YnognoZN8Vl13hanzMm0zV47ykkwgZixR-VEz1n_8vpfwopZ9-ZvhkBrAsjNCw9zgzSffrZlypMijnQE6vlzlAajld8HnTsAvJKaVriW3zhFzi4NwsPYc0Q3Fb4lepHgWAbFCOjcr6',
    rotate: -6,
    top: '2%',
    left: '8%',
    aspect: '3/4',
    width: '20rem',
    delay: 0.1,
    direction: 'right' as const,
  },
  {
    url: 'https://lh3.googleusercontent.com/aida-public/AB6AXuA_9FD_ohMA_CMT5M_MN_WkTf3z5JeOn74B5782t6_byUjAetJk5vu9x3tlv_AVNUx1FhA_tMG_9FuC-aBhMNDeWfx7h0QGRPPv1CMVnZj-PbRMAYk6woTcqqbpuLHwGneFOnx2YPaF6xEkDlHujzfVGST4bUKKTMnnX6-u_gVw1BJYQDwDVRBZuvsEqvLUP9p2mZjTxBPnZjkO9pKXKz0jsV3TbEQ5P0dRVSXfQulasp_uwGIRa69Ci-QVoKlwtPyqzSQVazDBQ6cO',
    rotate: 2,
    top: '12%',
    left: '38%',
    aspect: 'video',
    width: '22rem',
    delay: 0.3,
    direction: 'up' as const,
  },
  {
    url: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBWDLLei7_KPGroiZnq9_2tIUh61oVwEvAIMFYn30S-Mnsko9vVp_NQyD1Ya6Hkb_aa_gctQgqDDCpa_tsitzAY0CSdknNDzCJFdCSuW2pEAF-wyrDVpmrRXboiBoud--t3mILVZz9VpDUx1ApiwVG_M88zX1hnXBUdiaw-LywOWpyo18yX2bMp7EaTUYlqLTEElOL6Sa2tGX1tB86aaYMIg_MzzEUUPqM8lHhiS2p5UGFbg75IJXTHF-oE6JWJc6CpPGMDjPyDwJQq',
    rotate: -2,
    top: '8%',
    right: '8%',
    aspect: '4/5',
    width: '22rem',
    delay: 0.2,
    direction: 'left' as const,
  },
  {
    url: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDZmkt-GnprN5U1x-uwujL1vk3hWaC7U23-rTxShI8R5NW2p6Uz7qw6t8Uxl2hcavH-rQyKSYKKc-2-5siBPfOowCSavKpeLavfw3Gta3HzIJI3vFCrdLmAHKit2bXFcMHKJx2OyQXQM7ucpCoxhz0J1MMWGVMmrmzqoYCxmh0GDaehAjiM4G5bXggRalVAZedeSHiV41AX5hcT8EC4awY74WskFXEyfLu4tI9CTBFV7aTglrYEWgB3M9zMFLMEI6Ry-MANapdTYTrt',
    rotate: 5,
    bottom: '8%',
    left: '12%',
    aspect: 'video',
    width: '22rem',
    delay: 0.4,
    direction: 'right' as const,
  },
  {
    url: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCbmkqUqrwTi6_xIC9m0bNo-QiaXGJ56I8SJlXXA0va5-fcsNc_s3tJ-2ZYbOAaJF1JhpHZKoBauY9khFpga6Uzppkflk74PZKhhvV3CsoquQ4ecpaJQvWQZnu6h9KN62EOabCtjnbEWZIB7ufcSI-giSqloLDTHYbtvyo6D3oxqt8TslIds97ObBeqUhXCs9LwGyOr9aNZ-ru04a7rb6OzYP-FMKDmuB2YkXQLBmpamICZ5x3njEiNv2XrNrFWavD7hQOueb2yYv6I',
    rotate: -6,
    bottom: '2%',
    left: '42%',
    aspect: '3/4',
    width: '18rem',
    delay: 0.5,
    direction: 'up' as const,
  },
  {
    url: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDnwvZQMzFhPt2NTuRbETH1cROsallz6iNuxk1P5jWRDMI-heyGmAR6_csUIRmYabRAgaOEBPgBW-wQrbYjSgQIhE7PajECmorj6Ai1Z_7TKK83jKmN4pDNmoj_eZ77dAzclmUhU_p1xU_EDzLdQPoxszy80ZEoHNbHFWcTPHY6G7was_l_RBjz7NA93wOdCAmasJgreHGRgZtnMhv2tw-6iGtAWceKneP60yOqvsbPc1vEyBuwoNc5R4WKKoErhwT8mfeEK4y0fE0S',
    rotate: 3,
    bottom: '12%',
    right: '8%',
    aspect: 'video',
    width: '26rem',
    delay: 0.6,
    direction: 'left' as const,
  },
];
